# Agent Teams
- name: "team:core"
  color: "5319E7"
  description: "Core AI UI Generator implementation"

- name: "team:devops"
  color: "0E8A16"
  description: "DevOps, infrastructure, and tooling"

- name: "team:docs"
  color: "0075CA"
  description: "Documentation and guides"

- name: "team:testing"
  color: "D93F0B"
  description: "Testing, TDD, and QA"

- name: "team:features"
  color: "FBCA04"
  description: "Feature roadmap and backlog"

- name: "team:quality"
  color: "B60205"
  description: "Code quality and cleanup"

# Priority
- name: "priority:critical"
  color: "B60205"
  description: "Must be done immediately"

- name: "priority:high"
  color: "D93F0B"
  description: "Should be done soon"

- name: "priority:medium"
  color: "FBCA04"
  description: "Normal priority"

- name: "priority:low"
  color: "0E8A16"
  description: "Nice to have"

# Type
- name: "type:feature"
  color: "5319E7"
  description: "New feature or enhancement"

- name: "type:bug"
  color: "B60205"
  description: "Something isn't working"

- name: "type:docs"
  color: "0075CA"
  description: "Documentation improvements"

- name: "type:test"
  color: "D93F0B"
  description: "Testing related"

- name: "type:chore"
  color: "666666"
  description: "Maintenance and chores"

- name: "type:refactor"
  color: "FBCA04"
  description: "Code refactoring"

# Status
- name: "status:blocked"
  color: "B60205"
  description: "Blocked by dependency"

- name: "status:in-progress"
  color: "FBCA04"
  description: "Currently being worked on"

- name: "status:review"
  color: "0E8A16"
  description: "Ready for review"

- name: "status:done"
  color: "0E8A16"
  description: "Completed"

# AI UI Generator specific
- name: "ai-ui-generator"
  color: "7057FF"
  description: "Related to AI UI Generator module"

- name: "breaking-change"
  color: "B60205"
  description: "Introduces breaking changes"

- name: "good-first-issue"
  color: "7057FF"
  description: "Good for newcomers"

- name: "help-wanted"
  color: "008672"
  description: "Extra attention is needed"
