/**
 * Next.js App Router Export
 * Convert Fabric.js designs to Next.js App Router components
 */

import { ExportedCode, ExportOptions } from '../../types/aiui';
import { cssObjectToString, fabricToCSS, fabricToTailwind, formatCode, generateId, kebabToPascal } from './utils';

/**
 * Detect if component should be client-side
 */
const shouldBeClientComponent = (objects: any[]): boolean => {
	// Check if any object requires client-side interactivity
	return objects.some(obj => {
		return obj.interactive || obj.onClick || obj.onHover || obj.hasEvents;
	});
};

/**
 * Generate Next.js App Router page component
 */
const generateNextJSPage = (
	objects: any[],
	options: ExportOptions,
	componentName: string
): string => {
	const { styling, typescript } = options;
	const useTailwind = styling === 'tailwind';
	const useStyledComponents = styling === 'styled-components';
	const useCSSModules = styling === 'css-modules';
	const isClient = shouldBeClientComponent(objects);

	let imports = [];
	if (isClient) {
		imports.push(`'use client';`);
		imports.push('');
	}

	if (useStyledComponents) {
		imports.push(`import styled from 'styled-components';`);
	}
	if (useCSSModules) {
		imports.push(`import styles from './${componentName}.module.css';`);
	}

	const renderObject = (obj: any, index: number): string => {
		const id = generateId('el');
		
		if (obj.type === 'text') {
			const className = useTailwind
				? fabricToTailwind(obj).join(' ')
				: useCSSModules
				? `styles.text_${index}`
				: useStyledComponents
				? ''
				: `text_${index}`;

			const element = `<div ${className ? `className="${className}"` : ''}>${obj.text || 'Text'}</div>`;
			return useStyledComponents
				? `<StyledText_${index}>${obj.text || 'Text'}</StyledText_${index}>`
				: element;
		}

		if (obj.type === 'rect' || obj.type === 'group') {
			const className = useTailwind
				? fabricToTailwind(obj).join(' ')
				: useCSSModules
				? `styles.box_${index}`
				: useStyledComponents
				? ''
				: `box_${index}`;

			const children = obj.objects
				? obj.objects.map((child: any, i: number) => renderObject(child, i)).join('\n      ')
				: '';

			const element = children
				? `<div ${className ? `className="${className}"` : ''}>\n      ${children}\n    </div>`
				: `<div ${className ? `className="${className}"` : ''} />`;

			return useStyledComponents && !children
				? `<StyledBox_${index} />`
				: useStyledComponents
				? `<StyledBox_${index}>\n      ${children}\n    </StyledBox_${index}>`
				: element;
		}

		return '';
	};

	const elements = objects.map((obj, index) => renderObject(obj, index)).join('\n    ');

	const component = `
${imports.join('\n')}

export default function ${componentName}() {
  return (
    <main className="${useTailwind ? 'container mx-auto px-4 py-8' : useCSSModules ? 'styles.container' : 'container'}">
      ${elements}
    </main>
  );
}
`;

	return formatCode(component);
};

/**
 * Generate Next.js metadata
 */
const generateMetadata = (componentName: string, typescript: boolean): string => {
	const metadataType = typescript ? ': Metadata' : '';

	return `
import type { Metadata } from 'next';

export const metadata${metadataType} = {
  title: '${componentName}',
  description: 'Generated by AI UI Generator',
};
`;
};

/**
 * Generate Next.js layout component
 */
const generateLayout = (componentName: string, styling: string, typescript: boolean): string => {
	const useTailwind = styling === 'tailwind';
	
	let imports = [`import type { Metadata } from 'next';`];
	
	if (useTailwind) {
		imports.push(`import './globals.css';`);
	}

	const propsType = typescript
		? `{ children: React.ReactNode }`
		: '';

	return `
${imports.join('\n')}

export const metadata: Metadata = {
  title: '${componentName}',
  description: 'Generated by AI UI Generator',
};

export default function RootLayout(${typescript ? `{ children }: ${propsType}` : '{ children }'}) {
  return (
    <html lang="en">
      <body>${useTailwind ? '\n        ' : ''}{children}${useTailwind ? '\n      ' : ''}</body>
    </html>
  );
}
`;
};

/**
 * Generate loading component
 */
const generateLoading = (): string => {
	return `
export default function Loading() {
  return (
    <div className="flex items-center justify-center min-h-screen">
      <div className="text-lg">Loading...</div>
    </div>
  );
}
`;
};

/**
 * Generate error component
 */
const generateError = (typescript: boolean): string => {
	const propsType = typescript
		? `{ error, reset }: { error: Error & { digest?: string }; reset: () => void }`
		: '{ error, reset }';

	return `
'use client';

export default function Error(${propsType}) {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen">
      <h2 className="text-2xl font-bold mb-4">Something went wrong!</h2>
      <button
        className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
        onClick={() => reset()}
      >
        Try again
      </button>
    </div>
  );
}
`;
};

/**
 * Generate CSS for Next.js component
 */
const generateNextJSCSS = (objects: any[], styling: string): string => {
	if (styling === 'tailwind' || styling === 'styled-components') {
		return '';
	}

	const generateObjectCSS = (obj: any, index: number): string => {
		const css = fabricToCSS(obj);
		const selector = obj.type === 'text' ? `.text_${index}` : `.box_${index}`;
		return `${selector} {\n${cssObjectToString(css)}\n}\n`;
	};

	const cssRules = objects.map((obj, index) => generateObjectCSS(obj, index)).join('\n');

	return `.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem 1rem;
}

${cssRules}

@media (max-width: 768px) {
  .container {
    padding: 1rem;
  }
}
`;
};

/**
 * Generate styled-components definitions
 */
const generateStyledComponents = (objects: any[]): string => {
	const generateStyledComponent = (obj: any, index: number): string => {
		const css = fabricToCSS(obj);
		const cssString = Object.entries(css)
			.map(([key, value]) => `  ${key.replace(/([A-Z])/g, '-$1').toLowerCase()}: ${value};`)
			.join('\n');

		const tag = obj.type === 'text' ? 'div' : 'div';
		return `const StyledText_${index} = styled.${tag}\`\n${cssString}\n\`;\n`;
	};

	return objects.map((obj, index) => generateStyledComponent(obj, index)).join('\n');
};

/**
 * Export design as Next.js code
 */
export const exportNextJS = (design: any, options: ExportOptions): ExportedCode => {
	const componentName = kebabToPascal(design.metadata?.screenName || 'GeneratedPage');
	const objects = design.design?.objects || [];

	const files: ExportedCode['files'] = [];

	// Main page component
	const ext = options.typescript ? 'tsx' : 'jsx';
	let componentCode = generateNextJSPage(objects, options, componentName);

	if (options.styling === 'styled-components') {
		const styledDefs = generateStyledComponents(objects);
		componentCode = componentCode.replace(
			`import styled from 'styled-components';`,
			`import styled from 'styled-components';\n\n${styledDefs}`
		);
	}

	files.push({
		path: `app/page.${ext}`,
		content: componentCode,
		language: 'typescript',
	});

	// Layout component
	files.push({
		path: `app/layout.${ext}`,
		content: formatCode(generateLayout(componentName, options.styling, options.typescript)),
		language: 'typescript',
	});

	// Loading component
	if (options.styling === 'tailwind') {
		files.push({
			path: `app/loading.${ext}`,
			content: formatCode(generateLoading()),
			language: 'typescript',
		});

		// Error component
		files.push({
			path: `app/error.${ext}`,
			content: formatCode(generateError(options.typescript)),
			language: 'typescript',
		});
	}

	// Style file
	if (options.styling === 'css') {
		files.push({
			path: `app/globals.css`,
			content: generateNextJSCSS(objects, options.styling),
			language: 'css',
		});
	} else if (options.styling === 'css-modules') {
		files.push({
			path: `app/${componentName}.module.css`,
			content: generateNextJSCSS(objects, options.styling),
			language: 'css',
		});
	}

	const dependencies: Record<string, string> = {
		next: '^14.0.0',
		react: '^18.0.0',
		'react-dom': '^18.0.0',
	};

	if (options.styling === 'styled-components') {
		dependencies['styled-components'] = '^6.0.0';
	}
	if (options.styling === 'tailwind') {
		dependencies.tailwindcss = '^3.0.0';
		dependencies.autoprefixer = '^10.0.0';
		dependencies.postcss = '^8.0.0';
	}

	return {
		files,
		dependencies,
		instructions:
			'This is a Next.js 14 App Router project. Place files in the correct directory structure. ' +
			(options.styling === 'tailwind'
				? 'Configure Tailwind CSS according to Next.js documentation.'
				: ''),
	};
};
