import { describe, it, expect } from 'vitest';
import { exportToReact, generateComponentCode, generateImports } from '../react';

describe('React Export', () => {
	describe('exportToReact', () => {
		it('should generate valid React component code', async () => {
			const design = {
				objects: [
					{ type: 'rect', left: 0, top: 0, width: 100, height: 50, fill: '#3B82F6' },
				],
			};

			const code = await exportToReact(design, { styling: 'tailwind', typescript: true });

			expect(code).toContain('export');
			expect(code).toContain('React');
		});

		it('should use Tailwind classes when specified', async () => {
			const design = { objects: [{ type: 'rect', fill: '#3B82F6' }] };
			const code = await exportToReact(design, { styling: 'tailwind', typescript: true });

			expect(code).toContain('className=');
			expect(code).toContain('bg-blue-500');
		});

		it('should include TypeScript types when typescript option is true', async () => {
			const design = { objects: [] };
			const code = await exportToReact(design, { styling: 'inline', typescript: true });

			expect(code).toContain('FC');
			expect(code).toContain(': FC');
		});

		it('should not include TypeScript types when typescript option is false', async () => {
			const design = { objects: [] };
			const code = await exportToReact(design, { styling: 'inline', typescript: false });

			expect(code).not.toContain(': FC');
		});

		it('should use inline styles when specified', async () => {
			const design = {
				objects: [
					{ type: 'rect', left: 10, top: 20, width: 100, height: 50, fill: '#3B82F6' },
				],
			};
			const code = await exportToReact(design, { styling: 'inline', typescript: true });

			expect(code).toContain('style={{');
		});

		it('should handle multiple objects', async () => {
			const design = {
				objects: [
					{ type: 'rect', fill: '#3B82F6' },
					{ type: 'textbox', text: 'Hello' },
				],
			};
			const code = await exportToReact(design, { styling: 'tailwind', typescript: true });

			expect(code).toContain('Hello');
		});
	});

	describe('generateImports', () => {
		it('should generate React import for TypeScript', () => {
			const imports = generateImports({ styling: 'inline', typescript: true });
			expect(imports).toContain("import React, { FC } from 'react'");
		});

		it('should generate React import for JavaScript', () => {
			const imports = generateImports({ styling: 'inline', typescript: false });
			expect(imports).toContain("import React from 'react'");
			expect(imports).not.toContain('FC');
		});

		it('should include styled-components import when using styled-components', () => {
			const imports = generateImports({ styling: 'styled-components', typescript: true });
			expect(imports).toContain("import styled from 'styled-components'");
		});

		it('should not include styled-components import for other styling options', () => {
			const imports = generateImports({ styling: 'tailwind', typescript: true });
			expect(imports).not.toContain('styled-components');
		});
	});

	describe('generateComponentCode', () => {
		it('should generate a component with the correct name', () => {
			const design = { objects: [] };
			const code = generateComponentCode(design, { styling: 'inline', typescript: false });

			expect(code).toContain('GeneratedComponent');
			expect(code).toContain('export');
		});

		it('should include comments when includeComments is true', () => {
			const design = { objects: [] };
			const code = generateComponentCode(design, {
				styling: 'inline',
				typescript: false,
				includeComments: true,
			});

			expect(code).toContain('// Generated by AI UI Generator');
		});

		it('should not include comments when includeComments is false', () => {
			const design = { objects: [] };
			const code = generateComponentCode(design, {
				styling: 'inline',
				typescript: false,
				includeComments: false,
			});

			expect(code).not.toContain('// Generated');
		});

		it('should handle rect objects', () => {
			const design = {
				objects: [{ type: 'rect', width: 100, height: 50, fill: '#3B82F6' }],
			};
			const code = generateComponentCode(design, { styling: 'tailwind', typescript: false });

			expect(code).toContain('<div');
		});

		it('should handle textbox objects', () => {
			const design = {
				objects: [{ type: 'textbox', text: 'Hello World', fontSize: 16 }],
			};
			const code = generateComponentCode(design, { styling: 'tailwind', typescript: false });

			expect(code).toContain('Hello World');
		});

		it('should handle circle objects', () => {
			const design = {
				objects: [{ type: 'circle', radius: 50, fill: '#3B82F6' }],
			};
			const code = generateComponentCode(design, { styling: 'tailwind', typescript: false });

			expect(code).toContain('<div');
		});

		it('should use Tailwind classes for colors', () => {
			const design = {
				objects: [{ type: 'rect', fill: '#3B82F6' }],
			};
			const code = generateComponentCode(design, { styling: 'tailwind', typescript: false });

			expect(code).toContain('bg-blue-500');
		});

		it('should generate container div', () => {
			const design = { objects: [] };
			const code = generateComponentCode(design, { styling: 'inline', typescript: false });

			expect(code).toContain('generated-container');
		});

		it('should handle empty objects array', () => {
			const design = { objects: [] };
			const code = generateComponentCode(design, { styling: 'inline', typescript: false });

			expect(code).toContain('return');
			expect(code).toContain('export');
		});
	});
});
